### ISSUE TITLE
Update for Robolectric 3.0-Snapshot

### ISSUE THREAD

**Issue by Semptic** [zbsz/robotest#1]
Hi,

could you update this to work with Robolectric 3.0-Snapshot?

Greetings

**Comment by zbsz** [comment]
I'm only using stable robolectric releases in my projects, so didn't have a need for that yet. I guess this could be good exercise to find out what's going to change in 3.0, so maybe will do it later. You could always just send a pull request :)

**Comment by zbsz** [comment]
Finally done, now supporting latest Robolectric 3.0 snapshot, subject to break at any point (if Robolectric api changes)
