### ISSUE TITLE
Publish 2.10 artifact

### ISSUE THREAD

**Issue by joprice** [zbsz/robotest#11]
Thanks for the great library! I'm currently integrating it into [macroid](https://github.com/47deg/macroid/pull/78), but it still needs to support 2.10. It looks like you have `crossScalaVersions`, but 2.10 artifact is not published. Would it be possible to publish it?

**Comment by zbsz** [comment]
Done, thanks for pointing that out.

```
<dependency>
  <groupId>com.geteit</groupId>
  <artifactId>robotest_2.10</artifactId>
  <version>0.12</version>
</dependency>
```

**Comment by joprice** [comment]
Thank you!
