### ISSUE TITLE
findLibraries override breaks project.properties

### ISSUE THREAD

**Issue by tek** [zbsz/robotest#7]
I'm unsure how to adapt to the changes in the library loading mechanism. I had been using project.properties to reference both local fs dependencies as well as exploded aars (android.support etc), which I manually placed in my project tree. You seem to be overriding robolectrics functionality completely by reading the `target/aars` dir.
I'm sporting a multi-project structure with several inter-project root deps, and the `aars` dir is only present in dep target dirs, not the test dir, which results in multiple problems.
First a NPE due to `target/aars` being absent. Circumventing this with `if (aarsDir.isDirectory)`, robolectric starts up but fails to find library resources.
Removing the `findLibraries` override works fine, the old mechanism loads the resources as usual.

Am I missing something obvious? Seems to me it would work if we were trying to find aars in all `target` dirs, but I assume this would be a sort of aggregation job for `android-sdk-plugin`…though I'm perfectly fine with using the previously working method, in which case we would need a config flag for `RobolectricSuite` to choose the library loading method.

**Comment by zbsz** [comment]
Very good point, I wrongly assumed that `aars` will be always working and just dropped `project.properties` support. Will add it back, plan is to check if `project.properties` exists and only search for `aars` if it doesn't. This should work for you, right?

**Comment by tek** [comment]
It would, though I don't see a reason why you shouldn't use both. It is possible to have an sbt project dep in project.properties and still want to rely on automatic aar addition.

**Comment by zbsz** [comment]
Right, was thinking that sometimes you could want to override a library from `aars` (use different one), but this should rarely be needed and you can always override `aarsDir` property in that case. Thanks for suggestion. Will do the changes asap.

**Comment by tek** [comment]
great, thanks. Anyhoo, the automatic method sounds a lot more intriguing, I wonder if @pfn can contribute something here? It would be very nice to be able to add libraries from a) the `aarsDir` of sbt dependencies and b) all sbt dependencies themselves that use `androidBuildAar` (or just those that export resources)

**Comment by zbsz** [comment]
Integration with android-plugin right now seems problematic, `robotest` in general shouldn't know anything about `sbt`, it is supposed to work with any build system as regular library.
Will need to think about it more, could you please provide an example project exposing that problem? Will be easier to talk/think about it once we have some test case.

**Comment by tek** [comment]
sure, will do.

**Comment by tek** [comment]
https://github.com/tek/robo_testcase_aarsdir

there ya go, mate. I guess it's just about reference type resources, the rest is aggregated anyway by android-sdk-plugin. If you run `test/test`, it'll print reference ids from the `app` intra-project dep and from `appcompat`. removing the libraries from `project.properties` results in the references to resolve to `0`.

**Comment by zbsz** [comment]
Thanks. Created new issue #8 for that.
